#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# setup-https.sh — Cài Caddy reverse proxy HTTPS cho school-bot
# Usage: bash scripts/setup-https.sh <your-domain.com>
# ============================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

DOMAIN="${1:-}"

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Thiếu domain.${NC}"
    echo "Usage: bash scripts/setup-https.sh <your-domain.com>"
    echo "VD:    bash scripts/setup-https.sh bot.myschool.com"
    exit 1
fi

# ── Kiểm tra DNS ────────────────────────────────────────────
echo -e "${YELLOW}[1/4]${NC} Kiểm tra DNS cho ${DOMAIN}..."
RESOLVED_IP=$(dig +short "$DOMAIN" @8.8.8.8 2>/dev/null || true)
if [ -z "$RESOLVED_IP" ]; then
    echo -e "${RED}Domain ${DOMAIN} chưa trỏ về IP nào.${NC}"
    echo "Cần tạo DNS A record: ${DOMAIN} → IP của VPS này."
    echo "Sau đó chạy lại script."
    exit 1
fi
echo -e "  ${GREEN}✓${NC} ${DOMAIN} → ${RESOLVED_IP}"

# ── Cài Caddy ───────────────────────────────────────────────
echo -e "${YELLOW}[2/4]${NC} Cài đặt Caddy..."

if command -v caddy &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Caddy đã có: $(caddy version | head -1)"
else
    if command -v apt-get &>/dev/null; then
        # Ubuntu/Debian
        sudo apt-get update -qq
        sudo apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        sudo apt-get update -qq
        sudo apt-get install -y -qq caddy
    elif command -v dnf &>/dev/null; then
        sudo dnf -y install 'dnf-command(copr)'
        sudo dnf -y copr enable @caddy/caddy
        sudo dnf -y install caddy
    else
        echo -e "${RED}Không detect được package manager. Cài Caddy thủ công:${NC}"
        echo "  https://caddyserver.com/docs/install"
        exit 1
    fi
    echo -e "  ${GREEN}✓${NC} Caddy installed: $(caddy version | head -1)"
fi

# ── Ghi Caddyfile ───────────────────────────────────────────
echo -e "${YELLOW}[3/4]${NC} Ghi cấu hình Caddy..."

CADDYFILE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CADDYFILE="${CADDYFILE_DIR}/Caddyfile"

# Dùng Caddyfile có sẵn trong project, thay {$DOMAIN} bằng domain thật
sudo mkdir -p /etc/caddy
sudo tee /etc/caddy/Caddyfile > /dev/null <<CADDY_EOF
# Generated by setup-https.sh for school-bot
# Domain: ${DOMAIN}

${DOMAIN} {
    reverse_proxy localhost:3000

    request_body {
        max_size 10MB
    }

    header {
        X-Frame-Options "DENY"
        -Server
    }
}
CADDY_EOF

echo -e "  ${GREEN}✓${NC} Đã ghi /etc/caddy/Caddyfile"

# ── Mở firewall ─────────────────────────────────────────────
echo -e "${YELLOW}[4/4]${NC} Mở port 80, 443..."

if command -v ufw &>/dev/null && sudo ufw status | grep -q "Status: active"; then
    sudo ufw allow 80/tcp 2>/dev/null || true
    sudo ufw allow 443/tcp 2>/dev/null || true
    echo -e "  ${GREEN}✓${NC} ufw: đã mở 80, 443"
elif command -v firewall-cmd &>/dev/null && sudo firewall-cmd --state 2>/dev/null | grep -q "running"; then
    sudo firewall-cmd --permanent --add-service=http --add-service=https 2>/dev/null || true
    sudo firewall-cmd --reload 2>/dev/null || true
    echo -e "  ${GREEN}✓${NC} firewalld: đã mở http, https"
else
    echo -e "  ${YELLOW}!${NC} Không detect firewall. Đảm bảo port 80 và 443 đã mở."
fi

# ── Khởi động Caddy ─────────────────────────────────────────
echo ""
echo "Khởi động lại Caddy..."
sudo systemctl enable caddy 2>/dev/null || true
sudo systemctl restart caddy 2>/dev/null || {
    # Fallback: chạy background nếu không có systemd
    echo "Không dùng được systemd, chạy Caddy ở background..."
    sudo caddy start --config /etc/caddy/Caddyfile
}

sleep 2

# ── Kiểm tra ────────────────────────────────────────────────
if curl -s -o /dev/null -w "%{http_code}" "https://${DOMAIN}/webhook" 2>/dev/null | grep -q "4..\|2.."; then
    echo ""
    echo -e "${GREEN}=============================================${NC}"
    echo -e "${GREEN}  Cài đặt thành công!${NC}"
    echo -e "${GREEN}=============================================${NC}"
    echo ""
    echo "  Webhook URL cho Meta:"
    echo -e "  ${GREEN}https://${DOMAIN}/webhook${NC}"
    echo ""
    echo "  Verify token: dùng giá trị FB_VERIFY_TOKEN trong .env"
    echo ""
else
    echo ""
    echo -e "${YELLOW}Không curl được https://${DOMAIN}/webhook${NC}"
    echo "Có thể đang chờ Let's Encrypt cấp chứng chỉ (thường vài giây)."
    echo "Kiểm tra trạng thái: sudo systemctl status caddy"
    echo "Log Caddy:           sudo journalctl -u caddy -f"
fi
